baseURL = 'https://w42.warpedvisions.org/'
languageCode = 'en-us'
title = 'warpedvisions.org'
theme = 'w42'

[params]
description = '[ESSAYS](/blog), [RECIPES](/food), AND [GENERAL MAKERY](/projects) BY [BRUCE ALDERSON](/pages/about-bruce-alderson).'
warpedScript = "/js/warped.js"
warpedStyle = "/css/warped.css"
disableSpecial1stPost = true
defaultTheme = "light"

[params.assets]
disableScrollBarStyle = true

[markup]
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
hl_inline = false
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = false
noHl = false
style = 'monokai'
tabWidth = 4
