baseURL = 'https://warpedvisions.org/'
languageCode = 'en-us'
title = 'warpedvisions.org'
tagline = 'ESSAYS, HOW-TO ARTICLES, AND GENERAL MAKERY BY [BRUCE ALDERSON](about-bruce-alderson).'
theme = 'w40'
