baseURL = 'https://warpedvisions.org/'
languageCode = 'en-us'
title = 'warpedvisions.org'
theme = 'w40'

[params]
description = 'ESSAYS, HOW-TO ARTICLES, AND GENERAL MAKERY BY [BRUCE ALDERSON](/pages/about-bruce-alderson).'
warpedScript = "/js/warped.js"
warpedStyle = "/css/warped.css"

disableSpecial1stPost = true

[params.assets]
disableScrollBarStyle = true
